---
title: "NO3_NH4_Calculations"
author: "MaryKBrady"
R version: "4.0.2 (2020-06-22) -- 'Taking Off Again'"
---
This code uses absorbance values to calculate ug NO3 or NH4 per g dry soil (see NO3_NH4_absorbances.Rmd to quickly get mean absorbance values for sample replicates from plate reader output). It will run through all the files in the designated folder so this folder should only contain files for this script. To run one file, still set the working directory but then type the file name or a list of file names into "file_names <-" instead of running list.files().

The user can set NH4 or NO3 at the top of the code but that only effects the name of the column in the output excel sheet. This ability is for clarity down the line and organizational purposes, it does not change anything about how the code functions.

The script will output the results as an excel file into the working directory folder with "_results" appended to each file name. If you wish to save to a folder other than the folder where the input files are stored, uncomment the two setwd lines (near beginning and end of the for loop) and put in the appropriate file paths. 

If you used a plate reader, each plate will probably need its own file unless you are using one set of standards for multiple plates (but you shouldn't do that).

The input files can be excel or csv. Note that excel files cannot run if they are open. Each input file must have these column headers (no caps):
code | soil_weight | kcl_vol | frac_wc | dilution | sample_vol | absorbance | standard | stnd_absorbance

code is the sample id, soil_weight is the wet weight in g of the soil used in the extraction (not dry weight equivalent), kcl_vol is the KCl used in the extraction in mL, frac_wc is the fractional water content of the soil (not including any water added for wet incubations) (fractional wc = wet-dry/wet), dilution is the amount in mL added to dilute the extraction (put 0 if no dilution), sample_vol is the volume of sample used/pipetted into each plate reader well in ml (not ul!), absorbance is the mean absorbance of replicates for the sample, standard is the ppm of the standards used for calibrating, and stnd_absorbance is the absorbance for the standards

Keep console open to view and respond to possible prompts and checks

```{r, message=F}
#install.packages("tidyverse")
#install.packages("openxlsx")
#install.packages("readxl")
library(tidyverse)
library(openxlsx)
library(readxl)

setwd("My_folder")    #folder for input files
file_names <- list.files()  #pulls all the files in the folder
NO3_NH4 <- "NO3" #or "NH4". used for column name in output

for (a in file_names) {
  #setwd(file path for input files, same as set above)  #use this line if input and output folders differ
#determine file type and use appropriate read function
  if (grepl(".xlsx", a) == T){   
    input <- read_excel(a, col_names = T)
  } else if (grepl(".csv", a) == T) {
    input <- read.csv(a, header = T)
  } else {
    stop(cat("Something went wrong reading file ", a, " Is it a .csv or .xlsx?"))
  }
#check column names
  for (b in c("code", "soil_weight", "kcl_vol", "frac_wc", "dilution", "sample_vol", "absorbance", "standard", "stnd_absorbance")){
    if (!(b %in% names(input))){
      stop(paste("column name", b, "not found in file", a))
    }
  }
#check for sample vol that might be in ul
  if (interactive()) { 
    if (max(input$sample_vol) >= 1){
      check_volume <- readline(prompt = cat("Warning: in file", a, "your sample_vol might be too high. Is ", max(input$sample_vol), " in ml and not ul? \nIf it is in ml type 'yes' then press enter to continue, if it is not in ml, type 'no' then press enter to stop the script"))
      if (check_volume == "no"){
        stop("please fix volumes")
      } else if (check_volume != "no" & check_volume != "yes"){
        stop("invalid entry")
      }
    }
  }
#separate samples and standards
  samples <- input %>% select(code | soil_weight | kcl_vol | frac_wc | dilution | sample_vol| absorbance) %>% 
    na.omit()
  standards <- input %>% select(standard | stnd_absorbance) %>% na.omit()               
#Calculate the calibration curve  
  regression <- lm(stnd_absorbance ~ standard, standards)   #creates calibration curve
  intercept <- as.numeric(coef(regression)[1])   #pulls out intercept from regression
  slope <- as.numeric(coef(regression)[2])       #pulls out slope from regression
  #summary(regression)                           #optional line to check R2, should be a really high R2
#calculate NO3 ppm
  samples <- samples %>%
    mutate(ppm = (absorbance-intercept)/slope)  #apply calibration curve to samples to get ppm
#blank correction
  blanks <- standards %>%
    filter(standard == 0) %>%  #pulls all 0 standards
    mutate(ppm = (stnd_absorbance-intercept)/slope)  #calculates ppm for blanks based on regression
  if ((max(blanks$stnd_absorbance)-min(blanks$stnd_absorbance)) > 0.01){#if diff btwn blanks absorbance is high
    if(interactive()){
      check_blank <-readline(prompt=cat("Warning: the difference between blanks absorbance is ", (max(blanks$stnd_absorbance)-min(blanks$stnd_absorbance)), " for file ", a,". This is a little high. \nType 'yes' and press enter to continue. Type 'no' and press enter to stop script and possibly remove anomalous/contaminated blanks."))
    }
    if(check_blank == "no"){
      stop()
    } else if (check_blank != "no" & check_blank != "yes") {
      stop("invalid entry")
    }
  }
  blank_correction <- mean(blanks$ppm) #average ppm of blanks
  samples <- samples %>%
    mutate(ppm = ppm - blank_correction) %>%  #subrtract avg blank value from all samples 
    mutate(ppm = case_when(ppm >= 0 ~ ppm, ppm < 0 ~ 0)) #if ppm is now negative, convert to 0
#ppm (blank corrected) to ug N per g dry soil  
  samples <- samples %>%
    mutate(mgN_L = ppm/(sample_vol/(sample_vol+dilution))) %>% #mgN per L, if no dilution it equals ppm
    mutate(mg = mgN_L*(kcl_vol/1000)) %>% #mg N
    mutate(dry_weight = (soil_weight - (soil_weight*frac_wc))) %>% #dry weight equivalent of soil
    mutate(ugN.per.gdry = (mg/dry_weight)*1000) #ug N per g dry soil
#calculate percent error (from the plate reader) for each sample -- optional
  #summ_obj <- summary(regression)
  #intercept_error <- summ_obj$coefficients[1,2]
  #slope_error <- summ_obj$coefficients[2,2]
  #samples <- samples %>%
    #mutate(calc_error = ppm * sqrt(((intercept_error/(absorbance-intercept))^2)+(slope_error/slope)^2)) %>%
    #mutate(percent_error = round(calc_error/ppm, digits = 2))
#save results
  N_results <- samples %>%
    select(code | ugN.per.gdry) #-- optional to add '| percent_error' to this line if you're calculating it
  names(N_results)[2] <- paste0("ug",NO3_NH4,".per.gdry")  #change column name to NO3 or NH4 as set at the top of code
  save_name <- sub(".csv", "", a) #remove .csv from file name
  save_name <- sub(".xlsx","", save_name) #remove .xlsx from file name
  #setwd(file path for output files)    #use this line if input and output folders differ
  write.xlsx(N_results, paste0(save_name, "_results.xlsx"))
}
```
