---
title: "NO3_absorbances"
author: "MKB"
R version: "4.0.2 (2020-06-22) -- 'Taking Off Again'"
---
This files takes the absorbance values from the plate reader excel output files and averages the replicates for each sample. It also calculates standard error for each sample. It will run through all the files in the designated folder so this folder should only contain files for this script. To run one file, still set the working directory but then type the file name into "files <-" instead of running list.files().

The output is an excel file with "_means" appended to the end of the file name. If you wish to save to a different folder than the folder where the input files are stored, uncomment the two setwd lines in the for loop and put in the appropriate file paths. 

This is set up to work with a 96 well tray (8 x 12) where each sample has three replicates going across the rows. An example is shown where letters are different samples:
A1 | A2 | A3 | B1 | B2 | B3 |C1 | C2 | C3 | D1 | D2 | D3
E1 | E2 | E3 | ...

```{r}
#install.packages("readxl")
#install.packages("openxlsx")
library(readxl)
library(openxlsx)

setwd("my_folder") #folder for input files
files <- list.files() #pulls all files from the folder
#standard error function
standard_error <- function(x){sd(x) / sqrt(length(x))}

for (a in files) {
  output <- matrix(nrow = 8, ncol = 8)
  colnames(output) <-c("mean 1-3", "stnd error 1-3", "mean 4-6", "stnd error 4-6", "mean 7-9", "stnd error 7-9", "mean 10-12", "stnd error 10-12")
  #setwd(file path for input files, same as working directory set above)  #set if input and output folders differ
  temp_file <- read_excel(a, col_names = F)
  for (b in 1:8) {
    c <- mean(as.numeric(temp_file[b,1:3]))
    c2 <- standard_error(as.numeric(temp_file[b,1:3]))
    d <- mean(as.numeric(temp_file[b,4:6]))
    d2 <- standard_error(as.numeric(temp_file[b,4:6]))
    e <- mean(as.numeric(temp_file[b,7:9]))
    e2 <- standard_error(as.numeric(temp_file[b,7:9]))
    f <- mean(as.numeric(temp_file[b,10:12]))
    f2 <- standard_error(as.numeric(temp_file[b,10:12]))
    output[b,] <- c(c,c2,d,d2,e,e2,f,f2)
  }
  save_name <- sub(".xlsx", "", a)
  #setwd(file path to folder for saving output files) #set if input and output folders differ  
  write.xlsx(output, paste0(save_name, "_means.xlsx"))
}
```
